import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Sidebar from "@/app/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="w-full h-full flex justify-center items-center relative bg-black overflow-y-auto">
            <div className="max-w-screen-lg w-full h-[calc(100vh-5rem)] flex">
              <Sidebar />
              {children}
            </div>
          </div>
      </body>
    </html>
  );
}
